### ISSUE TITLE
How to get defaultValue from schema

### ISSUE THREAD

**Issue by damii** [wittydeveloper/graphql-to-json-schema#10]
I need to get default value in InPut or Arg

input TestfieldInput {
  name: String!
  age: Int = 0
  zow: Boolean = true
  ognoo: DateTime
}

**Comment by damii** [comment]
Any idea?

**Comment by chavalipraveen** [comment]
Hi,

I have the exact same requirement. Any ideas on how to get it working? Or would it require a code change?

Thanks!
