### ISSUE TITLE
introspectionQuery imported as undefined

### ISSUE THREAD

**Issue by forstmeier** [wittydeveloper/graphql-to-json-schema#12]
I'm working on getting a copy-paste version of your test suite working but I'm running into the error that seems to indicate that the `introspectionQuery` imported from the `graphql` package is undefined.

```
Error: Must provide Source. Received: undefined.
```

Any insight into this would be super helpful.

**Comment by wittydeveloper** [comment]
Fixed in `graphql-2-json-schema@0.3.1-0`
