### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by newhouse** [wittydeveloper/graphql-to-json-schema#13]
Hi there - wondering if this library is still maintained?

If I submitted a PR to round-out the capability of `arguments` support in type fields to match the support that `arguments` already receive in queries and mutations, would you accept it? Or is there a reason that it's not implemented?

Thanks for this library!1

**Comment by wittydeveloper** [comment]
Hi @newhouse!

Yes, feel free to submit a PR and I'll take a look for merge 👀

**Comment by newhouse** [comment]
I will circle back with a proposed example input -> output for old vs new if I get the time, so we can at least make sure we like where I'm going before implementing...thanks!

**Comment by wittydeveloper** [comment]
`graphql-2-json-schema@0.3.1-0` published with all your fixes, thanks @newhouse 🙇🏼
