### ISSUE TITLE
NPM package is broken

### ISSUE THREAD

**Issue by newhouse** [wittydeveloper/graphql-to-json-schema#26]
Not 100% sure what your NPM deployment/publish strategy looks like, but it seems like you forgot to run the `ts` compiler so that the output is included in `dist/*` before publishing `0.3.0`?

See: https://npm.runkit.com/graphql-2-json-schema

> Error: Cannot find module '/app/available_modules/1611187942000/graphql-2-json-schema/dist/index.js'. Please verify that the package.json has a valid "main" entry

I don't see the `dist/` folder in the package...

**Comment by wittydeveloper** [comment]
Hi Chris!

Yes, the `0.3.0` version is broken, that's why I published the `0.3.0-0` right after 🤓

**Comment by newhouse** [comment]
Forgive me if I'm wrong here and going down the wrong path, but:
- You mean `0.3.1-0`, right? I don't see a `0.3.0-0` on [NPM](https://www.npmjs.com/package/graphql-2-json-schema).
- Either way, it seems like the `latest` tag is pointing to `0.3.0`, which will give people a broken package if the simply do `yarn add graphql-2-json-schema`

![image](https://user-images.githubusercontent.com/2524009/105397183-d0384b80-5bc4-11eb-9e35-b43f97ed59ed.png)

**Comment by wittydeveloper** [comment]
@newhouse you're right!
I just published `graphql-2-json-schema@0.3.1` ✅

**Comment by newhouse** [comment]
Thanks!
