### ISSUE TITLE
Cannot read property '__schema' of undefined

### ISSUE THREAD

**Issue by seventrust** [wittydeveloper/graphql-to-json-schema#4]
Cannot read property '__schema' of undefined when tryin' to read the schema introspection

**Comment by sbrichardson** [comment]
Currently, you have to provide a root `Query` in your GraphQL definition. If you provide just types/enums/inputs, it will give this error. `Mutation` isn't required.

depending on your types, you can make up a simple Query like

```gql
type Todo {
    id: String!
    name: String!
    completed: Boolean
    color: Color
}

Query {
  todo(id: String!): Todo
}

```
